server:
  port: 8072
 
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eurekaserver:8070/eureka/
      
 
spring:
  cloud:
    loadbalancer.ribbon.enabled: false
    gateway:
      enabled: true

      routes:
      - id: organization-service
        uri: lb://organization-service

        predicates:
        - Path=/organization/**
        filters:
        - RewritePath=/org/(?<path>.*), /$\{path}

      - id: licensing-service
        uri: lb://licensing-service
        predicates:
        - Path=/license/**
        filters:
        - RewritePath=/lic/(?<path>.*), /$\{path}

      # for the google link
      - id: google-link
        uri: https://www.google.com
        predicates:
          - Path=/google/**
        filters:
          - RewritePath=/google/(?<path>.*), /$\{path}
          # 200 status disables redirects
          - SetStatus=200 

      # # for the u of a link
      - id: arizona-link
        uri: https://www.arizona.edu
        predicates:
          - Path=/arizona/** 
        filters:
        # rewrite the path
          - RewritePath=/arizona/(?<path>.*), /$\{path} 
          - SetStatus=200
       
management:
  endpoints:
    web:
      exposure:
        include: "*"
        
        